FROM python:3
USER root
RUN pip install --upgrade pip
RUN pip install numpy
RUN pip install scipy
RUN pip install matplotlib
RUN pip install Pillow
RUN pip install keras
RUN pip install tensorflow
RUN pip install h5py
RUN pip install requests
RUN pip install beautifulsoup4
RUN pip install opencv-python
RUN pip install chainer
RUN pip install pixivpy
RUN pip install scikit-image
RUN pip install scikit-learn
RUN pip install pandas
